### ISSUE TITLE
Validate jdk8 & 9 patches have been forward ported

### ISSUE THREAD

**Issue by DanHeidinga** [ibmruntimes/openj9-openjdk-jdk10#12]
Concerns were raised in https://github.com/ibmruntimes/openj9-openjdk-jdk10/pull/11 that some of the patches to the jdk8 & 9 extension repos haven't been forward ported to jdk10 (and presumably, the jdk updates stream).

PR#11 identified missing windows build patches but there are likely others as well.

A comparison of the the repos needs to be done to ensure no required patches have been lost.

A policy to apply patches to the `jdk` stream (not yet open) and then backport to the 10, 9, 8 as required would prevent this kind of issue in the future.

**Comment by DanHeidinga** [comment]
https://github.com/eclipse/openj9/issues/1625 Suggests the SharedClasses patches are missing in the JDK10 stream.

**Comment by hangshao0** [comment]
I checked the patch to ModuleBootstrap.java (didn't check patches to other files). The following 4 lines are added before all the modules are mapped to their classLoaders: 
https://github.com/ibmruntimes/openj9-openjdk-jdk10/blob/openj9/src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java#L354-L357

But in Java 9, they are after all the modules are mapped to their classLoaders.
https://github.com/ibmruntimes/openj9-openjdk-jdk9/blob/openj9/jdk/src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java#L387-L391

This will break shared classes on platformClassLoader and appClassLoader.

**Comment by andrew-m-leonard** [comment]
I'll do a new compare with jdk9 to check nothing is missing.

The ModuleBootstrap patch I had to redo manually as the openjdk class had changed quite a bit and the patch would not merge, I thought I had done it right, obviously not :-)

**Comment by hangshao0** [comment]
> The ModuleBootstrap patch I had to redo manually as the openjdk class had changed ...

@andrew-m-leonard, are you fixing this ? If yes, I do not have to do it.

**Comment by andrew-m-leonard** [comment]
@hangshao0 yes, i'll do that along with the other issues I find
thanks

**Comment by andrew-m-leonard** [comment]
Merged into jdk10 and jdk11

**Comment by pshipton** [comment]
Thanks Andrew.

**Comment by DanHeidinga** [comment]
Going to second that!  Much appreciated @andrew-m-leonard for the work you and your team are doing with the Extensions repos.
