### ISSUE TITLE
jimage recreate option missing

### ISSUE THREAD

**Issue by jerrylui803** [ibmruntimes/openj9-openjdk-jdk10#48]
[https://adoptopenjdk.gitbooks.io/adoptopenjdk-getting-started-kit/en/intermediate-steps/openjdk9-jimage.html](https://adoptopenjdk.gitbooks.io/adoptopenjdk-getting-started-kit/en/intermediate-steps/openjdk9-jimage.html)
I think there should be a `./bin/jimage recreate` option, 
but there is only `Usage: jimage <extract | info | list | verify> <options> jimage...`

`jimage --version` is 10.0.1

I used `jimage -extract` to unzip, but is there a way to zip it back?

**Comment by pshipton** [comment]
> but is there a way to zip it back?

No, only jlink can create jimage files. The output of jimage extract doesn't contain sufficient information to recreate the jimage.

> I think there should be a ./bin/jimage recreate option

You'd have to take that up with the OpenJDK project.

**Comment by pshipton** [comment]
> I am trying replace some .class files that are packed inside `jdk10/lib/modules`. Do you know what's the best way to do this?

Use the --patch-module option
```
--patch-module <module>=<file>(:<file>)*
                     override or augment a module with classes and resources
                     in JAR files or directories.
```
