### ISSUE TITLE
Unable to launch jenkins build/sanity jobs from PR

### ISSUE THREAD

**Issue by adamfarley** [ibmruntimes/openj9-openjdk-jdk10#50]
I create PRs and write comments such as "Jenkins test sanity xlinux,plinux,zlinux,aix", but jenkins does not launch those jobs.

My assumption is that this doesn't work for me because I am not on the access whitelist, despite the fact that I am a committer for the extensions repositories.

Could someone please resolve this for me?

**Comment by pshipton** [comment]
@jdekonin fyi

**Comment by jdekonin** [comment]
Extensions repos utilize openj9 jenkins and machine resources to accomplish this task.  Documentation doesn't mention 10, but I can see the jobs on jenkins.

https://github.com/eclipse/openj9/tree/master/buildenv/jenkins

Committers list does not get automatically updated, but I am uncertain the process for getting added to this list.  Even were your `jenkins...` comment valid, not being on this list would block a pr launch.

Let me get back to you on this...

**Comment by jdekonin** [comment]
Automating the triggers portion of the jenkins jobs is the next step in resolving for [PR 2138](https://github.com/eclipse/openj9/pull/2138)

**Comment by adamfarley** [comment]
Thanks @jdekonin
